#spring:
#  profiles:
#    active:
#     - dev
#---
#spring:
#  profiles: dev     #开发环境
#  application:
#    name: microservicecloud-config-zf-dev
#---
#spring:
#  profiles: test    #测试环境
#  application:
#     name: microservicecloud-config-zf-test
#
#     #请保存为UTF-8格式
#spring:
#  profiles:
#    active:
#     - dev
#---
#server:
#  port: 8201
#spring:
#      profiles: dev
#      application: microservicecloud-config-client
#eureka:
#      client:
#        service-url:
#         defaultZone: http://eureka-dev.com:7001/eureka/
#
#---
#server:
#  port: 8202
#spring:
#      profiles: test
#      application: microservicecloud-config-client
#eureka:
#      client:
#        service-url:
#         defaultZone: http://eureka-dev.com:7001/eureka/